#!/usr/bin/env python3
import os
#print("Şu an ki dizinimiz;")
#print(os.getcwd())


filee = open("ornek.txt","w")
filee.write("icerisinde bunlar olacak.\nbak ayni zamanda bu da olacak haberin olsun.")
filee.close()
file2 = open("ornek.txt")
icerik = file2.read()
print(type(icerik))
al = icerik.replace("bunlar","sezer")
print(al)
file2.close()


